FROM python:3.10.12

WORKDIR /Case_Técnico

COPY . .

RUN pip install --no-cache-dir -r requirements.txt

RUN apt-get update && apt-get upgrade -y && apt-get install -y software-properties-common
RUN apt-get update && apt-get install -y default-jdk 
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/default-java

CMD ["python","main.py"]  